package uz.mc.apptender.utils;

public interface MessageConstants {
    String INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR";
    String USER_NOT_FOUND = "User not found!";
    String MUST_NOT_BE_NULL_ID = "MUST_NOT_BE_NULL_ID";
    String MUST_NOT_BE_NULL_CATEGORY_ID = "MUST_NOT_BE_NULL_CATEGORY_ID";
    String MUST_NOT_BE_NULL_USER_ID = "MUST_NOT_BE_NULL_USER_ID";
    String MUST_NOT_BE_NULL_TYPE = "MUST_NOT_BE_NULL_TYPE";
    String MUST_NOT_BE_NULL_KOD_SNK = "MUST_NOT_BE_NULL_KOD_SNK";
    String MUST_NOT_BE_BLANK_KOD_SNK = "MUST_NOT_BE_BLANK_KOD_SNK";
    String MUST_NOT_BE_BLANK_NAME = "MUST_NOT_BE_BLANK_NAME";
    String MUST_NOT_BE_NULL_NAME = "MUST_NOT_BE_NULL_NAME";
    String MUST_NOT_BE_BLANK_EDISM = "MUST_NOT_BE_BLANK_EDISM";
    String MUST_NOT_BE_NULL_EDISM = "MUST_NOT_BE_NULL_EDISM";
    String MUST_NOT_BE_NULL_NORMA = "MUST_NOT_BE_NULL_NORMA";
    String MUST_NOT_BE_NULL_RASHOD = "MUST_NOT_BE_NULL_RASHOD";
    String MUST_NOT_BE_NULL_PRICE = "MUST_NOT_BE_NULL_PRICE";
    String MUST_NOT_BE_NULL_SUMMA = "MUST_NOT_BE_NULL_SUMMA";
    String FULL_AUTHENTICATION_REQUIRED = "FULL_AUTHENTICATION_REQUIRED";
}
