server:
  port: 2481
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root123

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  file:
    name: tenders.log

app:
  admin:
    username: tender
    password: ygb237buw


